import { IconName } from './types'

export const ICON_ALT_MAP: { [key in IconName]: string } = {
  'arrow-down': '아래 화살표',
  'arrow-down-blue': '파란색 아래 화살표',
  'arrow-left-active': '활성화된 왼쪽 화살표',
  'arrow-left-disabled': '비활성화된 왼쪽 화살표',
  'arrow-up-red': '빨간색 위 화살표',
  'assignment-active': '활성화된 과제',
  'assignment-inactive': '비활성화된 과제',
  'box-blue': '파란색 상자',
  'box-red': '빨간색 상자',
  'calendar': '달력',
  'car-active': '활성화된 차량',
  'car-inactive': '비활성화된 차량',
  'celebration': '축하',
  'checkbox-active': '활성화된 체크박스',
  'checkbox-inactive': '비활성화된 체크박스',
  'checkbox-minus': '체크박스 빼기',
  'clock': '시계',
  'cloud-active': '활성화된 클라우드',
  'cloud-inactive': '비활성화된 클라우드',
  'dashboard-active': '활성화된 대시보드',
  'dashboard-inactive': '비활성화된 대시보드',
  'delete': '삭제',
  'download': '다운로드',
  'edit': '편집',
  'edit-button': '편집 버튼',
  'eye-close': '눈 닫기',
  'eye-open': '눈 열기',
  'filter-active': '활성화된 필터',
  'filter-inactive': '비활성화된 필터',
  'groups-active': '활성화된 그룹',
  'groups-inactive': '비활성화된 그룹',
  'inventory-active': '활성화된 재고',
  'inventory-inactive': '비활성화된 재고',
  'list-active': '활성화된 목록',
  'list-inactive': '비활성화된 목록',
  'manager': '매니저',
  'more': '더 보기',
  'payments': '결제',
  'price': '가격',
  'processing': '처리 중',
  'radio-active': '활성화된 라디오 버튼',
  'radio-inactive': '비활성화된 라디오 버튼',
  'search': '검색',
  'upload-active': '활성화된 업로드',
  'upload-inactive': '비활성화된 업로드',
  'user-active': '활성화된 사용자',
  'user-inactive': '비활성화된 사용자',
}
